/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author MoaathAlrajab
 */
import java.util.Scanner;
public class Homework09 {
//for some reason my program keeps printing 1 number for some input?
public static void main(String[] args) {

    Scanner itterate = new Scanner(System.in);
    System.out.println("What number do you want to check?");
    int x = itterate.nextInt();
    int n = 1;
    int num = 1;
    int count = 0;

    while (count <= x) {
        n++;
        num += n;
        count = count(num);
    }

    System.out.println("The first triangle number with over " + x + " divisors is " + num);
}

public static int count(int num) {
    int count = 0;
    for (int i = 1; i <= Math.sqrt(num); i++) {
        if (num % i == 0) {
            count += 2;
        }
    }
    if (Math.sqrt(num) * Math.sqrt(num) == num) {
        count--;
    }
    return count;
}

    // ToDo 01:  Write an algorithm to solve the following problem
    /*
    The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over one hundred divisors?
    
    */
    
    
}
